version: "3"

services:
  mongo-server:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      GEO_PASS: ${GEO_PASS}
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./files_and_data/database_files:/data/db
    networks:
      - default
    stdin_open: true
    tty: true
  #    ports:
  #      - 127.0.0.1:27017:27017

  flask-app:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./api_server
    volumes:
      - ./logs/flask-logs:/home/flaskuser/flaskapp/log
      - ./files_and_data/static:/home/flaskuser/flaskapp/static
    networks:
      - default
    stdin_open: true
    tty: true

    depends_on:
      - mongo-server
    ports:
      - 127.0.0.1:5000:5000

  nginx-server:
    restart: always
    build:
      context: ./nginx_server
      dockerfile: Dockerfile
    volumes:
      - ./logs/nginx-logs:/var/log/nginx
      - ./nginx_server/build:/docker_nginx/html
      - ./nginx_server/ssl:/etc/nginx/ssl
    ports:
      - 80:80
      - 443:443
    networks:
      - default
    stdin_open: true
    tty: true
    depends_on:
      - flask-app

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24
