#!/bin/bash

if [[ ${UID} -ne 0 ]]
then
    echo "ERROR: You are not root"
    echo "Switch to root account by running: sudo su -"
    exit 1
fi

if [[ ${#} -eq 0 ]] 
then
    echo -e "ERROR: No FILE-URI provided"
    echo -e "Usage: $(basename ${0}) FILE-URI"
    echo -e "FILE-URI is the URI of file in S3 bucket in the format s3://<s3-bucket>/<filename>"
    exit 1
fi

cleanup() {
    cd ~
    if [[ -a ${DIRNAME} ]]
    then
        rm -rf ${DIRNAME}
    fi
}
DIRNAME="db-restore"
FILENAME="$(basename ${1})"
FILE_URI="${1}"
S3_BUCKET="s3://mongo-backup-geo"
DB_NAME="geo"

cd ~
if [[ -a ${DIRNAME} ]]
then
    rm -rf ${DIRNAME}
fi

mkdir ${DIRNAME}
cd ${DIRNAME}

echo -e "\nDownloading file ${FILENAME}..."
aws s3 cp ${FILE_URI} ./${FILENAME} > /dev/null
if [[ ${?} -ne 0 ]]
then 
    echo -e "\nERROR: Downloading file failed. Please make sure the file URI is correct and you have permission."
    cleanup
    exit 1
fi

echo -e "\nExtracting tarball ${PWD}/${FILENAME}..."
tar xf ${FILENAME} 
if [[ ${?} -ne 0 ]]
then 
    echo -e "\nERROR: File extraction failed. Please make sure it is a tarball of the format .tar.gz"
    cleanup
    exit 1
fi

echo -e "\nRestoring database..."
cd db-backup
mongorestore -d review ./review
if [[ ${?} -ne 0 ]]
then 
    echo -e "\nERROR: DB restore failed. Please make sure mongodb is running."
    cleanup
    exit 1
fi

echo -e "\nDatabase restore complete"
exit 0
