#!/bin/bash

NGINX_FOLDER="geo_nginx"

if [[ ${2} == "-f" ]]
then
    rm -rf ${NGINX_FOLDER}/build 
fi

if ! [[ -d ${NGINX_FOLDER}/build ]]
then
    echo "Frontend site not found. Building.... "
    cd geo_dashboard

    if ! [[ -d node_modules ]] 
    then
        echo "Node modules not installed. Installing..."
        ncu -u 
        npm install 
    fi

    npm run build 
    if [[ ${?} -ne 0 ]]
    then
        echo "Error building frontend"
        exit 1
    else
        echo "Frontend built. Moving site..."
        mv build ../${NGINX_FOLDER}/
    fi
    cd ..
fi

echo "Starting production server..."
docker-compose --env-file docker.production.env up --build ${1}

