#!/bin/bash

NGINX_FOLDER="nginx_geo/sites"
SITE_FOLDER="geo.intellideep.digital/game"
ADMIN_SITE_FOLDER="admin.geo.intellideep.digital"
ADMIN_CODE_FOLDER="dashboard_geo"
FRONTEND_CODE_FOLDER="frontend_geo"

if [[ ${1} == "-f" ]]; then
    echo "Deleting folders: ${ADMIN_SITE_FOLDER}, ${SITE_FOLDER}"
    rm -rf ${NGINX_FOLDER}/${ADMIN_SITE_FOLDER}
    rm -rf ${NGINX_FOLDER}/${SITE_FOLDER}
    shift
fi

if ! [[ -d ${NGINX_FOLDER}/${ADMIN_SITE_FOLDER} ]]; then
    echo "Building admin site.... "
    cd ${ADMIN_CODE_FOLDER}

    if ! [[ -d node_modules ]]; then
        echo "Node modules not installed. Installing..."
        ncu -u
        npm install
    fi
    npm run build
    if [[ ${?} -ne 0 ]]; then
        echo "Error building admin site"
        exit 1
    else
        echo "Admin site built. Moving site..."
        mv build ../${NGINX_FOLDER}/${ADMIN_SITE_FOLDER}
    fi
    cd ..
fi

if ! [[ -d ${NGINX_FOLDER}/${SITE_FOLDER} ]]; then
    echo "Building frontend.... "
    cd ${FRONTEND_CODE_FOLDER}

    if ! [[ -d node_modules ]]; then
        echo "Node modules not installed. Installing..."
        ncu -u
        npm install
    fi
    npm run build
    if [[ ${?} -ne 0 ]]; then
        echo "Error building frontend"
        exit 1
    else
        echo "Frontend built. Moving site..."
        mv build ../${NGINX_FOLDER}/${SITE_FOLDER}
    fi
    cd ..
fi

echo "Starting production server..."
docker-compose --env-file docker.production.env up ${@}
