import datetime
import os
DEBUG = True
PROPAGATE_EXCEPTIONS = True
JWT_SECRET_KEY = os.environ["JWT_SECRET_KEY"]
JWT_BLACKLIST_ENABLED = True
JWT_BLACKLIST_TOKEN_CHECKS = ["access", "refresh"]
MAX_CONTENT_LENGTH = 16 * 1024 * 1024
JWT_ACCESS_TOKEN_EXPIRES=datetime.timedelta(minutes=15)
JWT_REFRESH_TOKEN_EXPIRES=datetime.timedelta(days=30)
TTL_SECONDS = 30 * 24 * 60 * 60
DELETED_ENTRY_TTL = 30 * 24 * 60 * 60

MAIL_USERNAME = os.environ["MAIL_USERNAME"]
MAIL_PASSWORD = os.environ["MAIL_PASSWORD"]
MAIL_SERVER = "127.0.0.1"
MAIL_PORT = 1025
MAIL_USE_TLS = True
