// export const MAIN_URL = "https://api.geo.intellideep.digital"
// export const MAIN_URL = "https://localhost:5000"
export const MAIN_URL = "http://localhost:3000"
export const IMAGE_URL = "http://localhost/static/images/countries"
// export const IMAGE_URL = "https://api.geo.intellideep.digital/static/images/countries/"
export const GET = "GET"
export const POST = "POST"

// Endpoints
export const EP_RAND_LIST = "/random-list"
export const EP_COUNTRY = "/published"

export const GAME_LENGTH = 5
export const CHOICE_COUNT = 9
export const FREE_ANS = 6

export const OUTER_CONTAINER = "outer_container"
export const LOADING = "loading"
export const MAIN = "main"
export const CARD = "card"
export const CARD_CONTAINER = "card_container"
export const SUBSECTION = "subsection"
export const SUBHEADING = "subheading"
export const LOADING_SCREEN_CONTAINER = "loading_screen_container"
export const SECTION = "section"
export const CARD_HERO_IMAGE = "card_hero_image"
export const CARD_TITLE = "card_title"
export const CARD_CLUES = "card_clues"
export const CARD_CHOICES = "card_choices"
export const CLUES = "clues"
export const Q_ANS_ITEM = "q_ans_item"
export const Q_ANS = "q_ans"
export const HERO_IMAGE_CONTAINER = "hero_image_container"
export const WORLD_MAP_CONTAINER = "world_map_container"
export const ANS_IMAGE_CONTAINER = "ans_image_container"
export const ANS_BELOW_IMAGE = "ans_below_image"
export const HERO_WORLD_MAP = "hero_world_map"
export const HERO_PERSON1 = "hero_person1"
export const HERO_PERSON2 = "hero_person2"
export const HERO_PERSON3 = "hero_person3"
export const CARD_HEADING = "card_heading"
export const HEADING = "heading"
export const BUTTON = "button"
export const BUTTON_SECONDARY = "button_secondary"
export const BUTTON_DISABLED = "button_disabled"
export const VIEW_HINTS_CONTAINER = "view_hints_container"
export const VIEW_HINTS_OUTER_CONTAINER = "view_hints_outer_container"
export const CORRECT_WRONG_ICON = "correct_wrong_icon"
export const CORRECT_ICON_CONTAINER = "correct_icon_container"
export const WRONG_ICON_CONTAINER = "wrong_icon_container"
export const VIEW_HINTS = "view_hints"
export const CHOICE_BUTTONS_CONTAINER = "choice_buttons_container"
export const CHOICES = "choices"
export const CONTAINER = "container"
export const SLIDE_IN = "slide_in"
export const SLIDE_IN_ICON = "slide_in_icon"
export const HIDE_ME = "hide_me"
export const SHOW_ME = "show_me"
export const Q_A_CONTAINER = "q_a_container"
export const QA_OUTER_CONTAINER = "qa_outer_container"
export const QA_INNER_CONTAINER = "qa_inner_container"
export const QUESTION = "question"
export const ANSWER = "answer"
export const VIEW_ANSWER = "view_answer"
export const ANS_YES = "ans_yes"
export const ANS_NO = "ans_no"
export const CORRECT_ANS = "correct_ans"
export const WRONG_ANS = "wrong_ans"
export const BUTTON_NEXT = "button_next"
export const ENDGAME = "endgame"

export const NETWORK_ERROR_CONTAINER = "network_error_container"
export const ERROR_MESSAGE = "error_message"
export const NETWORK_ERROR = "Error: Cannot connect to server. Please make sure your internet connection is working" +
                             " and try to refresh the page."

export const sleep = async(seconds) => {
    return new Promise(resolve => setTimeout(resolve, 1000*seconds))
}
